### ISSUE TITLE
Adicionar campos de redes sociais e whatsapp

### ISSUE THREAD

**Issue by juliabpp** [Coderockr/vitrine-social#272]

**Comment by hfxc** [comment]
Gostaria de participar dessa!

Tem mais informações sobre a task?

**Comment by lucassabreu** [comment]
@hfxc acho que acabamos tratando essa tarefa em algum outro momento... 

![image](https://user-images.githubusercontent.com/3457213/47012795-845fe780-d11b-11e8-8c7d-1e024318af43.png)

ainda tem essa issue, mas já esta em andamento... https://github.com/Coderockr/vitrine-social/issues/308

@juliabpp tem mais alguma coisa sobre esse assunto que precisaria ser tratada? ou esta tudo feito mesmo?

**Comment by juliabpp** [comment]
@hfxc na realidade essa seria outra tarefa. Hoje a organização tem um campo de website e telefone somente para colocarem o link e telefone. A ideia era ter website, facebook, instagram, whatsapp opcionais para que possam ter mais opções de contato.

**Comment by hfxc** [comment]
@juliabpp Eu posso adicionar esses campos então

**Comment by coderockrdev** [comment]
@hfxc ok!! Se tiver qualquer outra dúvida avisa!

**Comment by hfxc** [comment]
Eu to com um probleminha pra rodar o make serve, crio uma issue separada?

```
$: make serve
docker-compose up -d postgres
vitrine-social_postgres_1 is up-to-date
cd server && go run main.go serve
2018/10/17 00:40:44 notifying bugsnag: Container, getting the bucket location: RequestError: send request failed
caused by: Get https://s3.configRegion.amazonaws.com/images.vitrinesocial.org?location=: dial tcp: lookup s3.configRegion.amazonaws.com: no such host
panic: Container, getting the bucket location: RequestError: send request failed
caused by: Get https://s3.configRegion.amazonaws.com/images.vitrinesocial.org?location=: dial tcp: lookup s3.configRegion.amazonaws.com: no such host

goroutine 1 [running]:
github.com/Coderockr/vitrine-social/server/cmd.serveCmdFunc(0x1d4e7a0, 0x1d75360, 0x0, 0x0)
	/Users/hfxc/Repositories/vitrine-social/server/cmd/serve.go:64 +0x23d0
github.com/Coderockr/vitrine-social/server/cmd.withEnvironment.func1(0x1d4e7a0, 0x1d75360, 0x0, 0x0)
	/Users/hfxc/Repositories/vitrine-social/server/cmd/funcs.go:34 +0x136
github.com/spf13/cobra.(*Command).execute(0x1d4e7a0, 0x1d75360, 0x0, 0x0, 0x1d4e7a0, 0x1d75360)
	/Users/hfxc/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0x1d4e540, 0xc0001bdf48, 0x15fcf8e, 0x1d4e540)
	/Users/hfxc/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0x1d4e540, 0x10074d0, 0xc000080058)
	/Users/hfxc/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800 +0x2b
github.com/Coderockr/vitrine-social/server/cmd.Execute()
	/Users/hfxc/Repositories/vitrine-social/server/cmd/root.go:36 +0x2d
main.main()
	/Users/hfxc/Repositories/vitrine-social/server/main.go:20 +0x20
exit status 2
make: *** [serve] Error 1
```

**Comment by lucassabreu** [comment]
opa @hfxc, deve ter um arquivo `server/config/dev.env` no teu repositório, nele tem uma variável `STORAGE` com o valor `s3`, troque para ficar `STORAGE=local` e no `STORAGE_LOCAL_PATH` coloque um `/tmp` ou uma pasta para o upload de arquivos.

Pode deixar que vou criar uma issue para deixar essa parte da configuração mais clara.

**Comment by hfxc** [comment]
Há alguma ordem e formato desejados pra colocar os campos? No momento coloquei os três como campo largo em sequência Whatsapp, Facebook e Instagram, logo após Telefone.
![screen shot 2018-10-17 at 22 59 22](https://user-images.githubusercontent.com/13739505/47126766-6a7bed00-d260-11e8-9de7-5bc2a7c564d8.png)

Além disso algum dos novos campos deve possuir alguma máscara ou deixo aberto?

**Comment by lucassabreu** [comment]
achava bom o whatsapp ter a mesma máscara do telefone e nos do facebook e instagram serem links como é no campo de site

**Comment by RaonyMarcondes** [comment]
Para que o formulário não aparente ser extenso, o ideal seria subdividir em blocos, ou seja, jogar o input do telefone acima do input do site, e em seguida seccionar os grupos com headers ex:

### Dados Básicos
* nome
* email
* telefone
### Links / Redes Sociais
* site
* facebook
* instagram
* whatsapp
### Endereço
* ...
* ...

Lembrando que o Facebook e intagtam podem vir com as urls em prefixo (https://www.instagram.com/ e  https://www.facebook.com/ ). ex: 

![screen shot 2018-10-18 at 09 45 26](https://user-images.githubusercontent.com/1424842/47155166-9461fd80-d2ba-11e8-8d9d-cb865594c718.png)

**Comment by hfxc** [comment]
Fiz duas versões, uma usando o mesmo item do Galeria de Imagens e a outra usando o Divider o antd pra realmente seccionar os grupos, seguem as imagens:

![screen shot 2018-10-18 at 23 57 41](https://user-images.githubusercontent.com/13739505/47195878-4558ae80-d334-11e8-8bba-fa60c5ddb441.png)

![screen shot 2018-10-19 at 00 03 00](https://user-images.githubusercontent.com/13739505/47195883-4b4e8f80-d334-11e8-9c9b-6a6cbeb2e8fb.png)

Pra fazer o prefixos do facebook e instagram usei o addonBefore do antd e joguei um estilo pra ficar mais próximo visualmente do input
